NUM_VM=2
IP_NW="192.168.56."
IP_START=100

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"


  (1..NUM_VM).each do |i|

  config.vm.define "ubuntu0#{i}" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu0#{i}"
    ubuntu.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"
    ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end
    ubuntu.vm.provision "shell", path: "../../vagrant-scripts/vagrant-ubuntu.sh"
  end

  end
end 
